---
# INSTALL .: `pre-commit install --overwrite --install-hooks`
# UPDATE ..: `pre-commit autoupdate`
default_language_version:
  python: python3.10
exclude: '\.svg$'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      # Generall Stuff
      - id: trailing-whitespace
      - id: mixed-line-ending
        args:
          - "--fix=lf"
      - id: end-of-file-fixer
      # VCS
      - id: check-merge-conflict
      # Config / Data Files
      - id: check-yaml
      # Python
      - id: debug-statements
      - id: requirements-txt-fixer
  # Prettier (HTML, JS, CSS, Markdownâ€¦)
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.4
    hooks:
      - id: prettier
        # exclude HTML templates (no Jinja2 support)
        exclude: 'source/_templates/.*\.html'
  # YAML
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.29.0
    hooks:
      - id: yamllint
  # Python: check syntax
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args:
          - "--select=F"
  # Python: reorder imports
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.9.0
    hooks:
      - id: reorder-python-imports
        args:
          - "--application-directories=.:source"
          - "--py38-plus"
  # Python: lint with black
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        args:
          - "--line-length=88"
          - "--target-version=py38"
  # local hooks
  - repo: local
    hooks:
      - id: guide-syntax
        name: check guide syntax
        language: script
        entry: .venv/bin/python check-guides.py --check
        files: source/guide_.+\.rst
